### ISSUE TITLE
Служебные файлы PyCharm в репозитории

### ISSUE THREAD

**Issue by PeganovAnton** [python-practice-b02-927/Kamenskikh_Pavel#16]
В репозитории есть папка `.idea`, которая содержит служебные файлы среды PyCharm. Эти файлы связаны со средствами разработки, установленными на Вашем  компьютере, и не нужны на других устройствах, а значит их не должно быть в репозитории. Чтобы лишние файлы не попадали в проект, нужно настроить `.gitignore`. 
1. Добавьте в файл `.gitignore` строку
```
**/.idea/
```
Эта строка сделает так, чтобы `git` не обращал внимания на содержимое папок `.idea`, где бы в репозитории они ни находились.
2. Перейдите в корень репозитория и выполните команду для удаления файлов из `git`. Удаляется папка `.idea` в корне и папки `.idea` из подпапок первого уровня (например `lab3_2/.idea`).
```bash
git rm -r --cached .idea */.idea
```
Выполнение команды `git-rm` необходимо, так как добавление строки в `.gitignore`, не ведет остановке контроля над уже отслеживаемыми файлами. Ключ `-r` нужен, чтобы команда была применена рекурсивно ко всем файлам и папкам в `.idea` и `*/.idea`. Ключ `--cached` нужен, чтобы файлы были удалены только из кэша `git`, а не из файловой системы.

**Comment by KPA927** [comment]
Ненужная папка удалена с удаленного репозитория.
